### ISSUE TITLE
Node eats all CPU if usePrettier is enabled

### ISSUE THREAD

**Issue by beliolfa** [nuxt-community/html-validator-module#11]
### Version
module:  0.1.6
nuxt: 2.14.8

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration

```
htmlValidator: {
    usePrettier: true,
  },
```

## Reproduction

When I run `yarn dev` it takes 2-3 minutes consuming all CPU, then it shows the warnings in console and loads the page.

#### What is expected?
Load the app without performance impact

#### What is actually happening?
Takes a lot to load and show validation errors

#### Steps to reproduce
set `usePrettier` to true and `yarn dev`

## Additional information
It is something weird because my coworkers can run it without any issue.
I'm on a Macbook 16" 2019 using Node 12.19.0

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

### Performance analysis?
![image](https://user-images.githubusercontent.com/12644599/106286972-8c89b580-6246-11eb-9824-9ac609e8863d.png)

**Comment by danielroe** [comment]
@beliolfa Would appreciate a reproduction, if you could. For example, is there an issue with [this CodeSandbox](https://codesandbox.io/s/green-sound-wsdcn?file=/nuxt.config.js)?

**Comment by beliolfa** [comment]
Hi @danielroe, the code sandbox just works. I noticed in my project that it also works if I comment the @nuxtjs/tailwindcss module.

I tried to reproduce it in a fresh nuxt project with @nuxtjs/tailwindcss but it is working there. I don't know what edge case I'm having on this project but I can not use this usePrettier feature.

**Comment by beliolfa** [comment]
Here's a codesandbox with the generated HTML. Thanks!

https://codesandbox.io/s/sad-tharp-0ysbo

**Comment by beliolfa** [comment]
Ok. You pointed me to the right track. The main issue here is Tailwind in development injects 100k+ lines of CSS. In our case with variants and responsive 200k+. That makes Prettier scan that huge file. Here is a minimal reproduction using a fresh Nuxt + a fresh tailwind module. https://github.com/64robots/html-validator-repro

If you run `yarn dev` is going to take at least 20 secs in rendering the page. If you increase the size of that CSS then it is exponential.

For us, the fix will be to set the `purge.enabled` to true even in dev. I can confirm that it fixes the issue.

Thank you for your time!
