### ISSUE TITLE
Problem with disabling rule

### ISSUE THREAD

**Issue by Kozioleczek** [nuxt-community/html-validator-module#120]
### Version
module: 0.5.0
nuxt: 2.15.7

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration

```
  htmlValidator: {
    usePrettier: true,
    failOnError: true,
    options: {
      extends: [
        'html-validate:document',
        'html-validate:recommended',
        'html-validate:standard'
      ],
      rules: {
        'svg-focusable': 'off',
        'no-unknown-elements': 'error',
        // Conflicts or not needed as we use prettier formatting
        'void-style': 'off',
        'no-trailing-whitespace': 'off',
        // Conflict with Nuxt defaults
        'require-sri': 'off',
        'attribute-boolean-style': 'off',
        'doctype-style': 'off',
        // Unreasonable rule
        'no-inline-style': 'off'
      }
    }
  }
```

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

## Reproduction
I have a problem with the srcset tag that is generated by the nuxt-picture component from the @nuxt/image library.

```
<div class="dcw-work-for__side dcw-work-for__side--right">
        <!-- [html-validate-disable attribute-allowed-values] -->
        <nuxt-picture
          :alt="activeCountry.name"
          class="dcw-work-for__globe"
          :src="`/globe/${activeCountry.id}.webp`"
        />
      </div>
```

#### What is expected?
To be able to disable the rule for this block, or to be able to adjust the configuration to disable the rule for this component

#### What is actually happening?
Well, I am getting a message about invalid srcset tag. This is probably because nuxt-picture adds line breaks for subsequent variations of the image.
![image](https://user-images.githubusercontent.com/39913427/129714663-48e8ecc0-f547-4525-9ac4-20f94197ff95.png)

**Comment by danielroe** [comment]
@Kozioleczek Have you tried turning the rule off?

```diff
  htmlValidator: {
    usePrettier: true,
    failOnError: true,
    options: {
      extends: [
        'html-validate:document',
        'html-validate:recommended',
        'html-validate:standard'
      ],
      rules: {
        'svg-focusable': 'off',
        'no-unknown-elements': 'error',
        // Conflicts or not needed as we use prettier formatting
        'void-style': 'off',
        'no-trailing-whitespace': 'off',
        // Conflict with Nuxt defaults
        'require-sri': 'off',
        'attribute-boolean-style': 'off',
        'doctype-style': 'off',
        // Unreasonable rule
        'no-inline-style': 'off',
+       // https://html-validate.org/rules/attribute-allowed-values.html
+       'attribute-allowed-values': 'off',
      }
    }
  }
```

**Comment by Kozioleczek** [comment]
@danielroe Yes I did. RIght now I've got this rule disabled, but I created this issue with hope that there is possibility to just turn off that rule for specific attribute like for "srcset". 

If there is no such possibility then I'll just leave that rule disabled.

**Comment by danielroe** [comment]
@Kozioleczek I think this is probably an issue/question for [html-validate](https://gitlab.com/html-validate/html-validate) itself rather than this module.
