### ISSUE TITLE
No duplicated attribute errors everywhere

### ISSUE THREAD

**Issue by Alphability** [nuxt-community/html-validator-module#3]
### Version
module: 0.1.1
nuxt: 2.14.7

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration
No specific configuration.

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

### Steps to reproduce
Use nested components or scoped styles.

https://github.com/raWINce/nuxt-duplicate-data-v-attribute

### What is expected?
Ignore the duplicated attributes by default or **directly solve those errors since they're related to nuxt/vue core**.

### What is actually happening?
Throwing errors all over the place.

**Comment by danielroe** [comment]
I'm of two minds on this as I think this is likely a bug in Vue that needs to be addressed - but I think there is no great problem ignoring `data-v-*` attributes in generated HTML.
