### ISSUE TITLE
List rule URLs inline

### ISSUE THREAD

**Issue by replygirl** [nuxt-community/html-validator-module#39]
### Is your feature request related to a problem? Please describe.

#12 addressed #1 by listing the URL of each error's associated rule below the list of errors.

When dropping this module into an existing project that has 50+ issues per page, this output is overwhelming in two ways:

- To get a link to a rule, one has to scroll up & down a lot
- Most of the links are duplicates

As a result, the list of URLs doesn't speed things up, and possibly slows things down because I have to scroll up to see the errors after each refresh until I'm through most of the page.

### Describe the solution you'd like to see

List each URL directly below the error as proposed in #1

### Describe alternatives you've considered

Filter out duplicates

**Comment by danielroe** [comment]
This should be fixed in `v0.3.1`. Let me know if you have a better suggestion for how to implement!
