### ISSUE TITLE
Inputs required attributes

### ISSUE THREAD

**Issue by Alphability** [nuxt-community/html-validator-module#4]
### Version
module: 0.1.1
nuxt: 2.14.7

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration
No specific configuration.

#### Steps to reproduce
Using nuxt generate after creating any component including an input with a type attribute.

#### What is expected?
We expect the module to tell us that there is no no HTML validation errors found since we declared the input's type.

#### What is actually happening?
Nuxt/Vue seems to add the type attribute only on the client side. So the module throws an error for a case that in the end isn't.

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by danielroe** [comment]
@Alphability You're right - how odd! However, this is a Nuxt bug and I've created an issue [there](https://github.com/nuxt/nuxt.js/issues) - as this module is right to report that as an error.
