### ISSUE TITLE
Attribute "crossorigin" and <style> in <div>

### ISSUE THREAD

**Issue by andrejsharapov** [nuxt-community/html-validator-module#6]
I installed the module and now two errors appear every time I start it:

```bash
HTML validation errors found for /page/index error: Attribute "crossorigin" should omit value (attribute-empty-style) at inline:36:7:
  34 |       rel="preconnect"
  35 |       href="https://fonts.gstatic.com/"
> 36 |       crossorigin=""
     |       ^^^^^^^^^^^
  37 |     />
  38 |     <link
  39 |       data-n-head="1"


error: Element <style> is not permitted as content in <div> (element-permitted-content) at inline:66:8:
  64 |   <body>
  65 |     <div id="__nuxt">
> 66 |       <style>
     |        ^^^^^
  67 |         #nuxt-loading {
  68 |           background: white;
  69 |           visibility: hidden;


2 errors found.
```

The first error appears when nuxt `google-fonts-module` is installed. This area cannot be edited, so there is always an error.

The second error occurs immediately when installing the nuxt out of the box and installing this module. This is the basic structure of an application's pages when it is created `npx create-nuxt-app <my-project>`

---
It's a long time to wait for changes from the nuxt side, therefore, you need a solution to ignore or disable these problems.

---

**UPD**
my package.json

```bash
	"nuxt": "^2.14.7",
    "@nuxtjs/google-fonts": "^1.2.0",
    "@nuxtjs/html-validator": "^0.1.3",
```

config

```bash
  buildModules: [
    '@nuxtjs/html-validator',
    '@nuxtjs/vuetify',
    '@nuxt/components',
    '@nuxtjs/google-fonts',
    '@nuxtjs/style-resources',
    '@nuxtjs/eslint-module',
    '@nuxtjs/stylelint-module',
  ],
```

**Comment by danielroe** [comment]
@andrejsharapov You can disable the rules that are flagging these issues within [the module options](https://html-validator.nuxtjs.org/). (The rules are listed in the error message above and you can find out more details at https://html-validate.org/rules/index.html.)

**Comment by andrejsharapov** [comment]
Yes, it helped to hide the errors. Thanks.

**Comment by retroriff** [comment]
Acording to [this page](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin), crossorigin allows an empty value. However the validator is showing this warning:

```
Attribute "crossorigin" should omit value 
<link data-n-head="ssr" data-hid="gf-preconnect" rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="">
```

It would be preferable to avoid the alert instead of hiding the error.

**Comment by andre-w2** [comment]
did you find a solution? I can't do it, here's the config. 
['@nuxtjs/html-validator', {
      failOnError: false,
      rules: {
        'attribute-boolean-style': 'off',
        { 'attribute-empty-style': 'off'
      }
    }],

**Comment by danielroe** [comment]
It would be good to raise this upstream on https://gitlab.com/html-validate/html-validate.
