### ISSUE TITLE
Document usage in dev only

### ISSUE THREAD

**Issue by nachogarcia** [nuxt-community/html-validator-module#7]
### Is your feature request related to a problem? Please describe.
I'm interested in using this plugin in the development cycle, but I don't want to add any performance overhead by adding this into production mode.

While creating the build for ssr, it says ℹ Using html-validate to validate server-rendered HTML.

### Describe the solution you'd like to see
It would be nice to have a section in the documentation regarding performance and local/production usage.

**Comment by danielroe** [comment]
@nachogarcia Rest assured the plugin is not bundled into your server and does not run in production mode, although it does validate *generated* HTML and therefore runs at generate-time. We can improve the documentation and (in particular) the message that appears.

**Comment by darthf1** [comment]
Does this also mean it should be a normal dependency and not a dev dependency?

I get `Error: Cannot find module '@nuxtjs/html-validator'` during build. 

https://html-validator.nuxtjs.org/#quick-start
