### ISSUE TITLE
Throw an error in CI

### ISSUE THREAD

**Issue by MoogyG** [nuxt-community/html-validator-module#93]
Before submitting a pull request, what do you think about making this module usable in CI by raising an error on hook "generate:done" if one error at least is met by html-validate ?

**Comment by danielroe** [comment]
I think that is a great idea, but let's make it opt in by passing an option to the module.

**Comment by MoogyG** [comment]
#96

**Comment by danielroe** [comment]
This should be released in `v0.5.0` - thank you so much ❤️
